# Homework 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [2]:
import numpy as np
a = np.diag(range(1,4))
a[a == 0] = 7
print(a)

[[1 7 7]
 [7 2 7]
 [7 7 3]]


2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [12]:
np.array(list(range(5)) * 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [27]:
X = np.random.randint(10,size = (10, 10))
X   
    

array([[4, 6, 5, 6, 4, 6, 9, 6, 8, 0],
       [8, 4, 4, 7, 9, 8, 2, 4, 2, 2],
       [2, 4, 6, 9, 0, 5, 3, 9, 5, 0],
       [3, 2, 4, 6, 3, 6, 8, 4, 7, 3],
       [1, 8, 7, 6, 8, 9, 6, 9, 1, 2],
       [3, 8, 2, 3, 6, 7, 1, 1, 2, 2],
       [4, 2, 0, 4, 9, 0, 3, 0, 2, 5],
       [4, 5, 7, 6, 3, 1, 3, 8, 5, 6],
       [5, 1, 9, 1, 3, 4, 4, 2, 9, 5],
       [2, 5, 3, 1, 4, 2, 5, 9, 1, 5]])

In [33]:
X - X.mean(axis=1,keepdims=True)


array([[-1.4,  0.6, -0.4,  0.6, -1.4,  0.6,  3.6,  0.6,  2.6, -5.4],
       [ 3. , -1. , -1. ,  2. ,  4. ,  3. , -3. , -1. , -3. , -3. ],
       [-2.3, -0.3,  1.7,  4.7, -4.3,  0.7, -1.3,  4.7,  0.7, -4.3],
       [-1.6, -2.6, -0.6,  1.4, -1.6,  1.4,  3.4, -0.6,  2.4, -1.6],
       [-4.7,  2.3,  1.3,  0.3,  2.3,  3.3,  0.3,  3.3, -4.7, -3.7],
       [-0.5,  4.5, -1.5, -0.5,  2.5,  3.5, -2.5, -2.5, -1.5, -1.5],
       [ 1.1, -0.9, -2.9,  1.1,  6.1, -2.9,  0.1, -2.9, -0.9,  2.1],
       [-0.8,  0.2,  2.2,  1.2, -1.8, -3.8, -1.8,  3.2,  0.2,  1.2],
       [ 0.7, -3.3,  4.7, -3.3, -1.3, -0.3, -0.3, -2.3,  4.7,  0.7],
       [-1.7,  1.3, -0.7, -2.7,  0.3, -1.7,  1.3,  5.3, -2.7,  1.3]])

4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [81]:
Y= np.random.randint(10,size = (10, 10))
Y

array([[1, 8, 9, 1, 5, 4, 5, 1, 6, 4],
       [8, 4, 1, 6, 7, 2, 8, 2, 7, 4],
       [6, 0, 7, 5, 9, 0, 6, 3, 2, 9],
       [3, 4, 2, 3, 9, 6, 2, 5, 6, 2],
       [8, 5, 7, 3, 1, 1, 4, 1, 1, 5],
       [0, 9, 6, 9, 5, 3, 5, 1, 2, 2],
       [4, 2, 9, 0, 7, 6, 1, 9, 0, 3],
       [5, 8, 5, 4, 2, 4, 3, 1, 4, 6],
       [9, 8, 7, 4, 9, 3, 6, 2, 3, 2],
       [2, 8, 3, 6, 9, 4, 7, 0, 9, 7]])

In [80]:
Y - np.median(Y,axis=0,keepdims=True)

array([[ 1. , -1. ,  1. , -0.5,  2. ,  4. ,  3.5,  3. ,  4.5, -4. ],
       [-1. ,  4. , -1. ,  1.5,  1. ,  2. ,  1.5,  2. ,  0.5,  4. ],
       [-4. , -1. ,  2. ,  5.5, -5. , -5. ,  1.5,  2. , -2.5, -4. ],
       [ 0. , -2. ,  2. ,  5.5, -2. , -2. , -3.5, -6. ,  1.5,  4. ],
       [ 5. , -1. ,  1. ,  5.5,  1. , -5. , -3.5,  2. , -1.5, -3. ],
       [ 4. , -3. , -2. , -3.5, -1. ,  0. , -2.5, -4. , -2.5, -5. ],
       [ 0. ,  4. , -6. , -1.5, -4. ,  0. , -3.5,  1. ,  3.5,  1. ],
       [ 1. ,  2. , -3. , -1.5,  0. , -3. , -1.5, -3. , -0.5,  0. ],
       [-3. ,  5. ,  2. , -0.5,  1. ,  3. ,  5.5, -1. ,  3.5,  1. ],
       [-3. ,  1. , -6. ,  0.5,  0. ,  1. ,  2.5, -4. , -4.5,  0. ]])

5) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [51]:
x = np.random.randint(10,size = (10, 10))
x.max(axis =1,keepdims=True)
x.min(axis =1,keepdims=True)
np.concatenate((x,x.max(axis =1,keepdims=True),x.min(axis =1,keepdims=True)),axis = 1)

array([[9, 6, 5, 6, 8, 5, 4, 5, 5, 5, 9, 4],
       [8, 3, 5, 6, 4, 7, 8, 1, 7, 5, 8, 1],
       [3, 2, 8, 3, 1, 2, 3, 9, 8, 9, 9, 1],
       [4, 1, 3, 5, 9, 1, 3, 5, 5, 8, 9, 1],
       [3, 5, 5, 6, 6, 1, 5, 8, 6, 7, 8, 1],
       [9, 5, 3, 2, 8, 1, 7, 0, 3, 8, 9, 0],
       [0, 3, 8, 4, 2, 0, 5, 5, 0, 0, 8, 0],
       [3, 3, 3, 6, 4, 3, 8, 9, 0, 0, 9, 0],
       [8, 0, 5, 3, 5, 8, 0, 8, 4, 7, 8, 0],
       [8, 4, 8, 0, 2, 5, 7, 3, 0, 2, 8, 0]])

6) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [77]:
a =np.mat(np.arange(1,50)[1::2]).reshape(4,6)
b =np.mat(np.arange(1,50)[2::2]).reshape(6,4)
print(a*b)
print(np.linalg.inv(a*b))


[[1246 1330 1414 1498]
 [2902 3130 3358 3586]
 [4558 4930 5302 5674]
 [6214 6730 7246 7762]]
[[-3.66503876e+11 -3.21853878e-04  1.09951163e+12 -7.33007752e+11]
 [-7.13272928e+11  2.16519213e+12 -2.19056547e+12  7.38646273e+11]
 [ 2.52605748e+12 -4.33038426e+12  1.08259606e+12  7.21730710e+11]
 [-1.44628068e+12  2.16519213e+12  8.45778175e+09 -7.27369231e+11]]


7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [79]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])